
CREATE TABLE IF NOT EXISTS USERS(
ID INT PRIMARY KEY AUTO_INCREMENT,
LOGIN varchar(10),
PASSWORD varchar(100),
NAME varchar(100),
ROLE varchar(10)
);

CREATE TABLE IF NOT EXISTS QUESTIONS(
ID INT PRIMARY KEY AUTO_INCREMENT,
QUESTION varchar(100),
TYPE_QUESTION varchar(10),
AUTHOR varchar(10),
DIFFICULTY varchar(10),
ANSWER varchar(100)
);